### ISSUE TITLE
Make yapecs work with Pytest?

### ISSUE THREAD

**Issue by anthonio9** [maxrmorrison/yapecs#2]
Hi, I've been playing with your penn repository recently as you may know already. One thing I'd love to see would be to add `yapecs` compatibility with pytest. It seems that pytest cannot accept the `--config` parameter that all the penn programs do, this makes it a bit harder to test things, when tests are strongly related to the configuration files. What do you think about such feature?

**Comment by maxrmorrison** [comment]
@CameronChurchwell and I added a [`yapecs.compose` ](https://github.com/maxrmorrison/yapecs?tab=readme-ov-file#yapecscompose) function to support this. You can find examples in [our unit tests](https://github.com/maxrmorrison/yapecs/blob/main/test/test_core.py). Let me know if you run into any troubles with it.
